FROM vernemq/vernemq

COPY vernemq.conf /etc/vernemq/
COPY postgres_cockroach_commons.lua /vernemq/share/lua/auth

EXPOSE 1883
EXPOSE 4369
EXPOSE 8080
EXPOSE 8883
EXPOSE 8888
EXPOSE 9109
EXPOSE 44053
